name: Python - build and upload packages

on:
  push:
    branches:
      - 'main'
    tags:
      - 'python-v*'
  pull_request:
    # FIXME: do not run this workflow for every PR
    paths:
      - 'python/**'
      - 'rust/**'
      - 'tests_data/**'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.conf.name }}
    runs-on: ${{ matrix.conf.runner }}
    strategy:
      matrix:
        conf:
          - name: linux
            runner: ubuntu-latest
          - name: windows
            runner: windows-latest
          - name: macos
            runner: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # pin@v5
        with:
          python-version-file: 'python/.python-version'

      # FIXME: remove this, this is just for testing workflow triggers via tag
      - name: Install uv
        if: "startsWith(github.ref, 'refs/tags/')"
        run: curl -LsSf https://astral.sh/uv/0.4.7/install.sh | sh

      # It's OK to use the default python version and not the specified one
      - name: Install all projects dependencies
        working-directory: python
        run: uv sync --all-extras --dev

      - name: Build the python package
        working-directory: python
        run: uv run ./scripts/build_python_package.py

      - name: List wheels
        working-directory: python
        run: python -c "import os; print('\n'.join(os.listdir('dist')))"

      - name: Upload wheels
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: actions/upload-artifact@v4
        with:
          name: '*.whl'
          path: dist
